apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 10.4.1
  name: grafana-config
  namespace: monitoring
stringData:
  grafana.ini: |
    [date_formats]
    default_timezone = UTC

    [server]
    # The public facing domain name used to access grafana from a browser
    #domain = localhost

    # The full public facing url you use in browser, used for redirects and emails
    # If you use reverse proxy and sub path specify full url (with sub path)
    #root_url = http://localhost/grafana/

    # Serve Grafana from subpath specified in `root_url` setting. By default it is `false`
    #serve_from_sub_path = true
type: Opaque
